YontafaeOBih.WebUI/Models/Content.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace YontafaeOBih.WebUI.Models
{
    public class Content
    {
        public int Id { get; set; }
        [DisplayName("اسم المحتوى")]
        public string ContentTitle { get; set; }
        [DisplayName("وصف المحتوى")]
        [AllowHtml]
        public string ContentDescription { get; set; }
        [DisplayName("صورة معبرة عن المحتوى")]
        public string ContentImage { get; set; }

        [DisplayName("نوع المحتوى")]
        public int CategoryId { get; set; }
        public string UserId { get; set; }


        public virtual Category Category { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

YontafaeOBih.WebUI/Models/ContentsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace YontafaeOBih.WebUI.Models
{
    public class ContentsViewModel
    {
        public string ContentTitle { get; set; }
        public IEnumerable<ApplyForThisContent> Items { get; set; }
    }
}

YontafaeOBih.WebUI/Controllers/ContentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using YontafaeOBih.WebUI.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace YontafaeOBih.WebUI.Controllers
{
    [Authorize]
    public class ContentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Contents
        public ActionResult Index()
        {
            var contents = db.Contents.Include(c => c.Category);
            return View(contents.ToList());
        }

        // GET: Contents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // GET: Contents/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName");
            return View();
        }

        // POST: Contents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Content content, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path); //على السيرفر
                content.ContentImage = upload.FileName ; //داتا بيز
                content.UserId = User.Identity.GetUserId();
                db.Contents.Add(content);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", content.CategoryId);
            return View(content);
        }

        // GET: Contents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", content.CategoryId);
            return View(content);
        }

        // POST: Contents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Content content, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string oldPath = Path.Combine(Server.MapPath("~/Uploads"), content.ContentImage);

                if (upload != null)
                {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path); 
                    content.ContentImage = upload.FileName ;   
                }
                db.Entry(content).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", content.CategoryId);
            return View(content);
        }

        // GET: Contents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // POST: Contents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Content content = db.Contents.Find(id);
            db.Contents.Remove(content);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

YontafaeOBih.WebUI/Views/Contents/Create.cshtml
@model YontafaeOBih.WebUI.Models.Content

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Create</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("Create", "Contents", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Content</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ContentTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ContentDescription, new { htmlAttributes = new { @class = "form-control", @id = "ContentDescription" } })
                @Html.ValidationMessageFor(model => model.ContentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload"/>
                @Html.ValidationMessageFor(model => model.ContentImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "نوع المحتوى", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    CKEDITOR.replace("ContentDescription");
</script>

YontafaeOBih.WebUI/Views/Contents/Delete.cshtml
@model YontafaeOBih.WebUI.Models.Content

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>حذف المحتوى</h2>

<h3>هل أنت متأكد من حذف المحتوى؟</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.ContentImage)"
                 class="thumbnail" style="width:48px; height:48px" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="تأكيد الحذف" class="btn btn-danger" /> |
            @Html.ActionLink("العودة إلى قائمة المحتويات", "Index")
        </div>
    }
</div>

YontafaeOBih.WebUI/Views/Contents/Details.cshtml
 @model YontafaeOBih.WebUI.Models.Content

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Content</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentDescription)
        </dt>

        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(@Html.DisplayFor(model => model.ContentDescription).ToString()))
            @*@Html.DisplayFor(model => model.ContentDescription)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.ContentImage)"
                  class="thumbnail" style="width:48px; height:48px" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

YontafaeOBih.WebUI/Views/Contents/Edit.cshtml
@model YontafaeOBih.WebUI.Models.Content

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Contents", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <div class="alert alert-danger" id="error-div" style="display:none">
            <span id="view-err"></span>
        </div>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ContentImage)

        <div class="form-group">
            @Html.LabelFor(model => model.ContentTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" id="myImage"/>
                 @Html.ValidationMessageFor(model => model.ContentImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="save"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section scripts{
    <script>
    $(function () {
        $("#save").click(function () {

            //Check if the input is Empty
            //if ($("#JobImage").val() == "") {
            //    $("#error-div").fadeIn();
            //    $("#view-err").append("رجاء قم باختيار صورة");
            //    return false;
            //}

            if ($("#myImage").val() != "") {
            //Check if the Image extension is valid
                var filename = document.getElementById("myImage").value;
            var extensionImg = filename.substr(filename.lastIndexOf('.') + 1);
            var validExtensions = ['jpg', 'png', 'gif', 'bmp'];
            if ($.inArray(extensionImg, validExtensions) == -1) {
                $("#error-div").fadeIn();
                $("#view-err").append("رجاء قم باختيار صورة بامتداد صحيح");
                return false;
            }

            //Check if the Image Size is valid (2 mb)
            var myFileSize = document.getElementById("myImage").files[0].size / 1024 / 1024;

            if (myFileSize > 2) {
                $("#error-div").fadeIn();
                $("#view-err").append("رجاء قم باختيار صورة حجمها أقل من 2 ميغا بايت");
                return false;
            }
            }
        });
    });
    </script>

}

YontafaeOBih.WebUI/Views/Contents/Index.cshtml
@model IEnumerable<YontafaeOBih.WebUI.Models.Content>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>قائمة المحتويات</h2>

<p>
    @Html.ActionLink("إضافة محتوى جديد", "Create")
</p>
<table class="table table-stripped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContentTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContentDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContentImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContentTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContentDescription)
        </td>
        <td>
            <img src="~/Uploads/@Html.DisplayFor(model => item.ContentImage)"
                 class="thumbnail" style="width:48px; height:48px" />
        </td>
        <td>
            @Html.ActionLink("تعديل", "Edit", new { id=item.Id }) |
            @Html.ActionLink("تفاصيل", "Details", new { id=item.Id }) |
            @Html.ActionLink("حذف", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>